tsconfig.app.json, vite.config.ts
> #5
> 절대 경로 적용
- tsconfig.app.json에 적용
- vite.config.js에 적용
=> chore: 절대 경로 적용(#5)

package-lock.json, package.json, src/utils/cn.ts, tsconfig.app.json, vite.config.ts
> #13
> cn 유틸리티 도입
- clsx 라이브러리 도입
- tailwind merge 라이브러리 도입
- 유틸 cn 도입
- 절대경로 utils 추가
=> feat: cn 유틸리티 도입(#13)

package.json, src/components/Icon.tsx, src/types/icon.ts, src/vite-env.d.ts, vite.config.ts
> #20 
> 아이콘 공통 컴포넌트 생성 및 타입 선언
- `vite.config.ts` 및 `vite-env.d.ts` 수정
- SVG 형식 아이콘 타입 정의 (`IconProps`)
- 아이콘 컴포넌트 `Icon.tsx` 생성 : 색상, 크기, className 등 props로 전달
=> feat: 아이콘 공통 컴포넌트 구현(#20)

.github/workflows/discord-notifications.yml
> #이슈번호
> 웹훅 커스텀 테스트
- .github/workflows/discord-notifications.yml에 파일 추가
=> chore: 웹훅 커스텀 테스트(#26)

.github/workflows/discord-notifications.yml
> #34
> 웹훅 파일 등록
- 웹훅 파일 완성본 등록
=> chore: 웹훅 파일 등록(#34)

src/components/dataTable/DataTable.tsx, src/components/dataTable/Pagination.tsx, src/components/dataTable/TableHeader.tsx, src/components/dataTable/TableRow.tsx, src/hooks/dataTable/usePagination.ts, src/hooks/dataTable/useSelection.ts, src/hooks/dataTable/useSort.ts, src/types/table.ts
> #16 
> 공통 컴포넌트 기본기능 + 추가기능 구현
- 기본 기능 : 표제목 입력, 받아오는 데이터에 따라 렌더링, 기본 UI 구현
- 외부에서 값을 받아서 쓸수있게 고침
- 표 데이터 렌더링 테스트 완료
- 페이지네이션 구현 완료
- 체크박스 구현 완료
- 정렬기능 구현완료
- 컴포넌트 코드 분리 완료
- 데이터테이블, 페이지네이션 컴포넌트 분리 완료
- 정렬기능 수정
- 불필요 코드 제거
- 배포, 배포 토글 스위치 UI 구현
=> feat: 표(테이블) 공통 컴포넌트 구현(#16)

src/types/table.ts
- table.ts 파일 업데이트
> #45 
> 타입 파일 업데이트
- 표(테이블) 컴포넌트 타입파일 table.ts 업데이트
=> fix: 표(테이블) 컴포넌트 타입 table.ts 파일 업데이트(#45)

src/components/common/Input.tsx
> #3
- prop 네이밍 명시적으로 변경
- 스타일 변경
=> feat: 인풋 컴포넌트 수정(#3)

src/components/common/Dropdown.tsx, src/constants/zIndexDefine.ts
> #4
- 불필요한 prop 제거
- ul 요소에 고정되있는 width 값 부모 요소에 너비에 따라가게 스타일 수정
- 다른 요소에 가려지지 않도록 position 및 z-index 적용
- z-index zIndexDefine파일에 상수로 관리
=> feat: 드롭다운 공통 컴포넌트 수정(#4)

.github/workflows/build-test.yml
> #73
> build-test action 대상 브랜치에서 main 제거
=> chore: build-test action 대상 브랜치에서 main 제거(#73)

.github/workflows/pr-merge-check.yml
> #77
> develop 브랜치가 최신상태인지 확인하는 github action 코드 추가
=> chore: develop 브랜치가 최신상태인지 확인하는 github action 코드 추가(#77)

src/components/common/Input.tsx
> #80 
> - InputProps에 min 속성 추가
=> fix: input 컴포넌트 type 수정 (#80)

src/constants/urls.ts, src/hooks/data-table/usePagination.ts, src/pages/courses/Subjects.tsx, src/pages/quizzes/Deployments.tsx, src/pages/quizzes/Quizzes.tsx, src/pages/quizzes/Submissions.tsx, src/types/table.ts
> #98 
- 제목, 과목, 등록한 로고 POST 요청 기능구현 및 토스트 성공 실패 추가
- api 코드 수정
- table.ts 타입 수정
- usePagination.ts 수정, 페이지네이션 기능 수정
- 과정별 필터링 수정
- 검색 (조회) 기능 수정
=> feat: 쪽지시험 생성 기능구현(#98)

src/constants/urls.ts, src/pages/courses/Courses.tsx
=> feat: 과정목록 조회 페이지

package-lock.json, package.json, src/App.tsx, src/api/axiosInstance.ts, src/constants/button/button.ts, src/constants/urls.ts, src/hooks/useAuth.ts, src/pages/Login.tsx, src/pages/courses/Courses.tsx, src/pages/courses/Subjects.tsx, src/pages/quizzes/Deployments.tsx, src/pages/quizzes/Quizzes.tsx, src/types/user.ts, src/utils/cookies.ts, src/utils/navigation.ts, tsconfig.app.json, vite.config.ts
> #112 
- tsconfig.app.json , vite.config.js @api 경로 추가
- js-cookie 라이브러리 추가
- 로그인시 액세스 토큰, 리프레쉬 토큰 발급 로직 추가
- useAuth.ts, navigation.ts , cookies.ts 파일 추가
- 로그인 5회 시도 실패 시 로그인 차단 기능 추가
- 버튼 컴포넌트 스타일 추가
- 로그인 차단시 팝업 확인 버튼 추가
=> feat: 로그인 후 엑세스 토큰 받아오는 기능(#112)

src/components/quizzes/add-exam-modal/AddExamModal.tsx, src/components/quizzes/course-filter-modal/CourseFilterModal.tsx, src/pages/quizzes/Quizzes.tsx
=> refactor: quizzes 페이지 코드 리팩토링(#124)

src/api/generations/index.ts, src/api/instance/tokenHandler.ts, src/components/courses/add-courses-modal/AddCoursesModal.tsx, src/components/create-schedule/ScheduleModal.tsx, src/components/generations/add-generation-modal/AddGenerationModal.tsx, src/components/quizzes/add-exam-modal/AddExamModal.tsx, src/components/quizzes/detail-modal/DetailModal.tsx, src/components/subject/add-subject-modal/AddSubjectModal.tsx, src/hooks/useAuth.ts, src/pages/courses/Courses.tsx, src/pages/courses/Subjects.tsx, src/pages/quizzes/Deployments.tsx, src/utils/navigation.ts
> #137 
- 콘솔로그  코드 제거
- 기타 린트오류 코드 제거
=> chore: 모든 콘솔로그 코드 제거(#137)

index.html, src/api/quizzes/index.ts, src/components/quizzes/detail-modal/DetailModal.tsx, src/constants/button/button.ts, src/pages/quizzes/Quizzes.tsx, src/types/quizzes/quizTypes.ts
> #143
> 타이틀 수정, submitQuizData 최신화, 퀴즈페이지 버튼 수정
- index.html title 기본값에서 '오즈코딩스쿨 LMS ADMIN'으로 수정
- submitQuizData 요청 url 최신화, 데이터 타입 맞춰서 수정
- 배포중일때 버튼 스타일 수정
=> feat: 타이틀 수정, submitQuizData 최신화, 퀴즈페이지 버튼 수정(#143)

vite.config.ts
=> fix: CORS 오류 해결(#148)

src/api/courses/index.ts, src/api/generations/index.ts, src/components/generations/add-generation-modal/AddGenerationModal.tsx, src/components/subject/add-subject-modal/AddSubjectModal.tsx, src/constants/urls.ts, src/hooks/queries/useCoursesDropdown.ts, src/pages/quizzes/Quizzes.tsx, src/types/courses.ts
> #145 
- 과목 등록 모달 적용
- 기수 등록 모달 적용
=> feat: 과정 드롭다운 api 수정(#145)

src/pages/courses/Courses.tsx
> #156 
> courseDetailModal을 등록modal 밖으로 이동
=> fix: 과정 상세 모달 페이지 안 열리는 오류 수정(#156)

README.md
=> docs: README.md 작성(#162)
